### ISSUE TITLE
How to install plugin from lite-xl/lite-xl-plugins repository?

### ISSUE THREAD

**Issue by juliardi** [TorchedSammy/Miq#5]
Hi, thank you for developing Miq, this is a nice plugin for Lite XL. This plugin can install plugin both from a specified github repository and from a local directory. But, how to install a single file plugin from [lite-xl/lite-xl-plugins](https://github.com/lite-xl/lite-xl-plugins) repository?

**Comment by sammy-ette** [comment]
I didn't add that functionality yet but I can do it later today

**Comment by uni-dos** [comment]
Any update on this?

**Comment by sammy-ette** [comment]
hm.
i have a few other projects that i work on, but i *may* do it tomorrow

**Comment by uni-dos** [comment]
No rush. I can give it a shot, but I don't know much lua.

**Comment by sammy-ette** [comment]
So now this feature has been added, you can simple add it with the name specified on the lite-xl-plugins readme to your plugin spec, as shown on the readme here.
